<?php /*
	*
	* -------------------------------------------------------
	* CLASSNAME:        lidmaatschap
	* GENERATION DATE:  08.09.2013
	* CLASS FILE:       c:\wamp\www\\class.lidmaatschap.php
	* FOR MYSQL TABLE:  lidmaatschap
	* FOR MYSQL DB:     dbloi1
	* -------------------------------------------------------
	* CODE GENERATED BY:
	* MY PHP-MYSQL-CLASS GENERATOR
	* from: >> www.voegeli.li >> (download for free!)
	* -------------------------------------------------------
	*
	*/
	include_once("resources/class.database.php");
	// **********************
	// CLASS DECLARATION
	// **********************
	
	class lidmaatschap
	{ // class : begin
	
	
	// **********************
	// ATTRIBUTE DECLARATION
	// **********************
	
	var $;   // KEY ATTR. WITH AUTOINCREMENT
	
	var $id;   // (normal Attribute)
	var $ledenid;   // (normal Attribute)
	var $datumingang;   // (normal Attribute)
	var $datumeinde;   // (normal Attribute)
	var $sportonderdeel;   // (normal Attribute)
	var $lesdag;   // (normal Attribute)
	
	var $database; // Instance of class database
	
	
	// **********************
	// CONSTRUCTOR METHOD
	// **********************
	
	function lidmaatschap()
	{
	
	$this->database = new Database();
	
	}
	
	
	// **********************
	// GETTER METHODS
	// **********************
	
	
	function getid()
	{
	return $this->id;
	}
	
	function getledenid()
	{
	return $this->ledenid;
	}
	
	function getdatumingang()
	{
	return $this->datumingang;
	}
	
	function getdatumeinde()
	{
	return $this->datumeinde;
	}
	
	function getsportonderdeel()
	{
	return $this->sportonderdeel;
	}
	
	function getlesdag()
	{
	return $this->lesdag;
	}
	
	// **********************
	// SETTER METHODS
	// **********************
	
	
	function setid($val)
	{
	$this->id =  $val;
	}
	
	function setledenid($val)
	{
	$this->ledenid =  $val;
	}
	
	function setdatumingang($val)
	{
	$this->datumingang =  $val;
	}
	
	function setdatumeinde($val)
	{
	$this->datumeinde =  $val;
	}
	
	function setsportonderdeel($val)
	{
	$this->sportonderdeel =  $val;
	}
	
	function setlesdag($val)
	{
	$this->lesdag =  $val;
	}
	
	// **********************
	// SELECT METHOD / LOAD
	// **********************
	
	function select($id)
	{
	
	$sql =  "SELECT * FROM lidmaatschap WHERE  = $id;";
	$result =  $this->database->query($sql);
	$result = $this->database->result;
	$row = mysql_fetch_object($result);
	if($row){
	
	$this->id = $row->id;
	
	$this->ledenid = $row->ledenid;
	
	$this->datumingang = $row->datumingang;
	
	$this->datumeinde = $row->datumeinde;
	
	$this->sportonderdeel = $row->sportonderdeel;
	
	$this->lesdag = $row->lesdag;
	}else{return false};
	}
	
	// **********************
	// DELETE
	// **********************
	
	function delete($id)
	{
	$sql = "DELETE FROM lidmaatschap WHERE  = $id;";
	$result = $this->database->query($sql);
	
	}
	
	// **********************
	// INSERT
	// **********************
	
	function insert()
	{
	$this-> = ""; // clear key for autoincrement
	
	$sql = "INSERT INTO lidmaatschap ( id,ledenid,datumingang,datumeinde,sportonderdeel,lesdag ) VALUES ( '$this->id','$this->ledenid','$this->datumingang','$this->datumeinde','$this->sportonderdeel','$this->lesdag' )";
	$result = $this->database->query($sql);
	$this-> = mysql_insert_id($this->database->link);
	
	}
	
	// **********************
	// UPDATE
	// **********************	
	function update($id)
	{
	$sql = " UPDATE lidmaatschap SET  id = '$this->id',ledenid = '$this->ledenid',datumingang = '$this->datumingang',datumeinde = '$this->datumeinde',sportonderdeel = '$this->sportonderdeel',lesdag = '$this->lesdag' WHERE  = $id ";
	$result = $this->database->query($sql);
	
	}
	} // class : end	
	?>