<?php /*
	*
	* -------------------------------------------------------
	* CLASSNAME:        lidmaatschap
	* GENERATION DATE:  08.09.2013
	* CLASS FILE:       c:\wamp\www\\class.lidmaatschap.php
	* FOR MYSQL TABLE:  lidmaatschap
	* FOR MYSQL DB:     dbloi1
	* -------------------------------------------------------
	* CODE GENERATED BY:
	* MY PHP-MYSQL-CLASS GENERATOR
	* from: >> www.voegeli.li >> (download for free!)
	* -------------------------------------------------------
	*
	*/

	// **********************
	// CLASS DECLARATION
	// **********************
	
	class lidmaatschap
	{ 
// class : begin
	
	
	// **********************
	// ATTRIBUTE DECLARATION
	// **********************
	
	
	var $id;   // (normal Attribute)
	var $lidnummer;   // (normal Attribute)
	var $datumingang;   // (normal Attribute)
	var $datumeinde;   // (normal Attribute)
	var $sportonderdeel;   // (normal Attribute)
	var $lesdag;   // (normal Attribute)
	
	
	
	
	// **********************
	// CONSTRUCTOR METHOD
	// **********************
	
	public function __construct(  ){
	
	}
	public function update($data){          
            foreach($data as $key=> $val)
                        $this->{$key}=$val;                         
         return true;   
        }
	

        public function formfields(){
         return get_object_vars($this);   
        }

       public function save(){
            return $this->insert();       
        }

	
	private function insert(){
        $this->id = ""; //autoinc.
        $datumingang=$this->datumingang;                 
        $datumeinde=$this->datumeinde;
        $datumingang=$this->sqldate($datumingang);
        $datumeinde=$this->sqldate($datumeinde);
        $insertSQL = "INSERT INTO lidmaatschap ( id,lidnummer,datumingang,datumeinde,sportonderdeel,lesdag ) VALUES ( '$this->id','$this->lidnummer','$datumingang','$datumeinde','$this->sportonderdeel','$this->lesdag' )";
	$result= $this->queryExecute( $insertSQL );
        if ( $result )
            $this->id= mysql_insert_id();
        return $result;
	}
    private function queryExecute( $query )
    {
        //var_dump($query); 
        global $database_connection;
        global $connection;
        mysql_select_db( $database_connection, $connection );
        $result = mysql_query( $query, $connection ) or die( "verbinding met de database werd verbroken:" . mysql_error() );
        
        if ( $result === TRUE )
            $this->id = mysql_insert_id();
        
        return $result;
    }
    public function data(){
      $data="<table>
        <tr><td>Ingangsdatum </td><td>{$this->datumingang}</td></tr>
        <tr><td>Einddatum </td><td>{$this->datumeinde}</td></tr>
        <tr><td>Einddatum </td><td>{$this->datumeinde}</td></tr>
        <tr><td>Lesdag </td><td>{$this->lesdag}</td></tr>
        <tr><td>Sportonderdeel </td><td>{$this->sportonderdeel}</td></tr>        
      </table>";  
        return $data;
    }
    private function sqldate($dmy){
      $ymd=explode("/",$dmy);
      $sqldatum=$ymd[2].$ymd[1].$ymd[0];
      return $sqldatum;
    }
	} // class : end	
	?>